# Generated by Django 4.2.4 on 2023-11-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_patient_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(choices=[('E11', 'Type 2 Diabetes Mellitus'), ('I10', 'Hypertension'), ('F32', 'Major Depressive Disorder'), ('J20', 'Acute Bronchitis'), ('I10', 'Essential Hypertension'), ('M17', 'Osteoarthritis of Knee'), ('I21', 'Acute Myocardial Infarction'), ('J45', 'Asthma'), ('N39.0', 'Urinary Tract Infection'), ('M47.812', 'Cervical Spondylosis')], max_length=20),
        ),
    ]
