# Generated by Django 4.2.4 on 2023-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_mobileclinic_clinic_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population_density', models.IntegerField()),
                ('crisis_type', models.CharField(choices=[('E', 'Earthquake'), ('F', 'Floods'), ('T', 'Tornado')], max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('num_of_patients', models.IntegerField()),
                ('weather_status', models.CharField(choices=[('C', 'Cloudy'), ('S', 'Sunny'), ('R', 'Rainy')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('H', 'Health'), ('E', 'Education'), ('F', 'Finance')], max_length=1)),
                ('expiration_date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='mobileclinic',
            name='clinic_services',
            field=models.CharField(choices=[('H', 'Helth'), ('E', 'Education')], max_length=1),
        ),
    ]
