# Generated by Django 4.2.4 on 2023-10-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_activity_crisis_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='type',
            field=models.CharField(choices=[('Medical Equipment', 'Medical Equipment'), ('Medical Supplies', 'Medical Supplies'), ('Vaccines and Immunization', 'Vaccines and Immunization'), ('Diagnostic and Laboratory Equipment', 'Diagnostic and Laboratory Equipment'), ('Pharmaceutical Supplies', 'Pharmaceutical Supplies'), ('Emergency Response and Rescue Equipment', 'Emergency Response and Rescue Equipment')], max_length=100),
        ),
    ]
