# Generated by Django 4.2.4 on 2023-11-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_patient_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(choices=[('E11', 'E11'), ('I10', 'I10'), ('F32', 'F32'), ('J20', 'J20'), ('I10', 'I10'), ('M17', 'M17'), ('I21', 'I21'), ('J45', 'J45'), ('N39.0', ' N39.0'), ('M47.812', 'M47.812')], max_length=20),
        ),
    ]
