# Generated by Django 4.2.4 on 2023-09-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobileclinic',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
