# Generated by Django 4.2.4 on 2023-11-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_mobileclinic_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='mobile_clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='base.mobileclinic'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='base.activity'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='mobile_clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='base.mobileclinic'),
        ),
    ]
