# Generated by Django 4.2.4 on 2023-09-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_mobileclinic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='crisis_type',
            field=models.CharField(choices=[('Earthquake', 'Earthquake'), ('Floods', 'Floods'), ('Tornado', 'Tornado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='weather_status',
            field=models.CharField(choices=[('Cloudy', 'Cloudy'), ('Sunny', 'Sunny'), ('Rainy', 'Rainy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mobileclinic',
            name='clinic_services',
            field=models.CharField(choices=[('Health', 'Health'), ('Education', 'Education')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resources',
            name='type',
            field=models.CharField(choices=[('Health', 'Health'), ('Education', 'Education'), ('Finance', 'Finance')], max_length=10),
        ),
    ]
