# Generated by Django 4.2.4 on 2023-09-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_activity_mobile_clinic_patient_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='mobile_clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mobileclinic'),
        ),
    ]
