# Generated by Django 4.2.4 on 2023-09-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('inActive', 'inActive')], max_length=20),
        ),
    ]
