# Generated by Django 4.2.4 on 2023-09-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='mobile_clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mobileclinic'),
        ),
    ]
